AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Echelon-Backend

  SAM Template for Echelon-Backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: API/authentication/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Timeout: 30
      Events:
        Authentication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/login
            Method: post
        CreateUser:
          Type: Api
          Properties:
            Path: /auth/user
            Method: post
  TestingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: API/testing/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        TestGameSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /test/game/session
            Method: post
        TestPlayerSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /test/player/session
            Method: post
  MatchmakingTopic:
    Type: AWS::SNS::Topic
  MatchmakingTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: 
        - !Ref MatchmakingTopic
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: OwnerPolicy
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref MatchmakingTopic
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref "AWS::AccountId"
        - Sid: MatchmakingGameLiftPolicy
          Effect: Allow
          Principal:
            Service: gamelift.amazonaws.com
          Action: SNS:Publish
          Resource: !Ref MatchmakingTopic
      
  #    TopicName: "EchelonMatchmakingTopic"
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
